mode: debug
port: 8099

logger:
  loglevel: debug
  logdir: ./
  logfilename: demo.log
  logformat: text
  logwriter: false

kafka:
  addresses: [ "127.0.0.1:9092" ]
  consumergroupid: test
  consumeroffsetsinitial: newest

redis:
  addresses: [ "127.0.0.1:6379" ]
  db: 0
  poolsize: 10

mongo:
  uri: mongodb://127.0.0.1:27017
  dbname: test

mysql:
  db-mysql:
    url: root:jun123456@(127.0.0.1:3306)/db1?charset=utf8mb4&parseTime=True&loc=Local
    max-idle-conns: 5
    max-open-conns: 200
